# Generated by Django 4.2.5 on 2023-09-26 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='poster',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.TextField(null=True),
        ),
    ]
