# Generated by Django 4.2.5 on 2023-09-26 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_product_date_added_remove_product_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='poster',
            field=models.URLField(max_length=255, null=True),
        ),
    ]
